M48
; DRILL file {KiCad (6.0.9)} date Fri 25 Nov 2022 00:28:22 EET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-25T00:28:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X48.365Y-63.15
X48.365Y-68.93
T2
X48.26Y-20.32
X48.26Y-111.76
X256.54Y-17.78
X256.54Y-114.3
T3
X50.8Y-15.24
X50.8Y-116.84
X91.44Y-15.24
X91.44Y-116.84
T0
M30
