M48
; DRILL file {KiCad (6.0.9)} date Mon 26 Dec 2022 01:44:19 EET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-26T01:44:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X47.095Y-63.15
X47.095Y-68.93
T2
X46.99Y-20.32
X46.99Y-111.76
X255.27Y-17.78
X255.27Y-114.3
T3
X49.53Y-15.24
X49.53Y-116.84
X90.17Y-15.24
X90.17Y-116.84
T0
M30
